---
output:
  github_document:
    toc: true 
    toc_depth: 3
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-"
)
```

---

Worrrd
---

Build word games using R.  Ya hearrrd?

Features:

  - Crossword Puzzle
  - Wordsearch
  
### Install worrrd

```{r eval = FALSE}
install.packages("devtools")
devtools::install_github("anthonypileggi/worrrd")
```

### Wordsearch

Create your very own custom wordsearch!  Worrrd.

```{r}
library(gamer)

# Simple word search
words <- c("alligator", "crocodile", "squirrel", "swordfish", "german shepherd", "panda", "wolf")
x <- wordsearch(words, r = 20, c = 20)
plot(x, solution = TRUE)
```

You can make it as hard as you want.  Go bananas!

```{r}
# All 50 States
library(datasets)
x <- wordsearch(state.name, r = 50, c = 50)
plot(x, solution = TRUE, letter_size = 2)
```


#### Crossword Puzzle

Oh, you're one of the more sophicated types that craves a crossword puzzle?  Worrrd.

```{r crossword-1}
words <- row.names(state.x77)
clues <- paste0(state.region, "ern state covering ", scales::comma(state.x77[, "Area"]), " square miles.")
x <- crossword(words, clues, r = 40, c = 40)
x
```

```{r}
plot(x, solution = TRUE)
```